id: P006712
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8873
  title: པདྨ་འབྱུང་གནས་ཀྱི་རྣམ་ཐར
  author: ''
  volumes:
    c574351b1bfa48738beb8c0bccfd5e5b:
      image_group_id: I1PD97307
      title: ''
      volume_number: 1
      total_pages: 730
      base_file: v001.txt
